language: node_js
node_js:
  - node
  - lts/*
script:
  - npm test
  - npx codecov
branches:
  only:
    - master
jobs:
  include:
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
